services:
  # astro:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "4321:4321"
  #   depends_on:
  #     - postgres
  #   volumes:
  #     - .:/harhar
  #     - /harhar/node_modules
  #   networks:
  #     - mynetwork

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/DATABASE_URL

volumes:
  pgdata:
networks:
  mynetwork:
    driver: bridge
