export const categoriesData = [
    { category: 'Business Services', subcategory: 'Accounting' },
    { category: 'Business Services', subcategory: 'Lawyer' },
    { category: 'Business Services', subcategory: 'Consultant' },
    { category: 'Business Services', subcategory: 'Marketing Agency' },
    { category: 'Business Services', subcategory: 'Real Estate Agency' },
    { category: 'Business Services', subcategory: 'Architect' },
    { category: 'Business Services', subcategory: 'Engineer' },
  
    { category: 'Food & Drink', subcategory: 'Restaurant' },
    { category: 'Food & Drink', subcategory: 'Coffee Shop' },
    { category: 'Food & Drink', subcategory: 'Bakery' },
    { category: 'Food & Drink', subcategory: 'Bar' },
    { category: 'Food & Drink', subcategory: 'Fast Food Restaurant' },
    { category: 'Food & Drink', subcategory: 'Ice Cream Shop' },
    { category: 'Food & Drink', subcategory: 'Food Truck' },
    { category: 'Food & Drink', subcategory: 'Pizza Restaurant' },
    { category: 'Food & Drink', subcategory: 'Vegetarian Restaurant' },
    { category: 'Food & Drink', subcategory: 'Wine Bar' },
    { category: 'Food & Drink', subcategory: 'Juice Shop' },
  
    { category: 'Health & Medical', subcategory: 'Doctor' },
    { category: 'Health & Medical', subcategory: 'Dentist' },
    { category: 'Health & Medical', subcategory: 'Chiropractor' },
    { category: 'Health & Medical', subcategory: 'Pharmacy' },
    { category: 'Health & Medical', subcategory: 'Veterinary Clinic' },
    { category: 'Health & Medical', subcategory: 'Physical Therapy Clinic' },
    { category: 'Health & Medical', subcategory: 'Optometrist' },
    { category: 'Health & Medical', subcategory: 'Mental Health Service' },
    { category: 'Health & Medical', subcategory: 'Hospital' },
    { category: 'Health & Medical', subcategory: 'Emergency Room' },
  
    { category: 'Home Services', subcategory: 'Plumber' },
    { category: 'Home Services', subcategory: 'Electrician' },
    { category: 'Home Services', subcategory: 'HVAC Contractor' },
    { category: 'Home Services', subcategory: 'Landscaper' },
    { category: 'Home Services', subcategory: 'Painter' },
    { category: 'Home Services', subcategory: 'Cleaning Service' },
    { category: 'Home Services', subcategory: 'Locksmith' },
    { category: 'Home Services', subcategory: 'Pest Control Service' },
    { category: 'Home Services', subcategory: 'Carpenter' },
    { category: 'Home Services', subcategory: 'Roofing Contractor' },
  
    { category: 'Retail', subcategory: 'Clothing Store' },
    { category: 'Retail', subcategory: 'Electronics Store' },
    { category: 'Retail', subcategory: 'Furniture Store' },
    { category: 'Retail', subcategory: 'Grocery Store' },
    { category: 'Retail', subcategory: 'Bookstore' },
    { category: 'Retail', subcategory: 'Jewelry Store' },
    { category: 'Retail', subcategory: 'Toy Store' },
    { category: 'Retail', subcategory: 'Sporting Goods Store' },
    { category: 'Retail', subcategory: 'Hardware Store' },
    { category: 'Retail', subcategory: 'Beauty Supply Store' },
  
    { category: 'Education', subcategory: 'School' },
    { category: 'Education', subcategory: 'Tutoring Service' },
    { category: 'Education', subcategory: 'University' },
    { category: 'Education', subcategory: 'Language School' },
    { category: 'Education', subcategory: 'College' },
    { category: 'Education', subcategory: 'Music School' },
    { category: 'Education', subcategory: 'Art School' },
    { category: 'Education', subcategory: 'Preschool' },
  
    { category: 'Entertainment', subcategory: 'Movie Theater' },
    { category: 'Entertainment', subcategory: 'Amusement Park' },
    { category: 'Entertainment', subcategory: 'Bowling Alley' },
    { category: 'Entertainment', subcategory: 'Concert Hall' },
    { category: 'Entertainment', subcategory: 'Night Club' },
    { category: 'Entertainment', subcategory: 'Dance Studio' },
    { category: 'Entertainment', subcategory: 'Arcade' },
    { category: 'Entertainment', subcategory: 'Museum' },
    { category: 'Entertainment', subcategory: 'Zoo' },
    { category: 'Entertainment', subcategory: 'Comedy Club' },
  
    { category: 'Beauty & Personal Care', subcategory: 'Hair Salon' },
    { category: 'Beauty & Personal Care', subcategory: 'Nail Salon' },
    { category: 'Beauty & Personal Care', subcategory: 'Spa' },
    { category: 'Beauty & Personal Care', subcategory: 'Barber Shop' },
    { category: 'Beauty & Personal Care', subcategory: 'Massage Therapist' },
    { category: 'Beauty & Personal Care', subcategory: 'Skin Care Clinic' },
    { category: 'Beauty & Personal Care', subcategory: 'Tanning Salon' },
  
    { category: 'Travel & Transport', subcategory: 'Car Rental' },
    { category: 'Travel & Transport', subcategory: 'Travel Agency' },
    { category: 'Travel & Transport', subcategory: 'Taxi Service' },
    { category: 'Travel & Transport', subcategory: 'Hotel' },
    { category: 'Travel & Transport', subcategory: 'Limo Service' },
    { category: 'Travel & Transport', subcategory: 'Airport Shuttle Service' },
    { category: 'Travel & Transport', subcategory: 'Moving Company' },
    { category: 'Travel & Transport', subcategory: 'Bus Station' },
    { category: 'Travel & Transport', subcategory: 'Train Station' },
    { category: 'Travel & Transport', subcategory: 'Cruise Agency' },
  
    { category: 'Automotive', subcategory: 'Auto Repair Shop' },
    { category: 'Automotive', subcategory: 'Car Dealership' },
    { category: 'Automotive', subcategory: 'Auto Body Shop' },
    { category: 'Automotive', subcategory: 'Car Wash' },
    { category: 'Automotive', subcategory: 'Tire Shop' },
    { category: 'Automotive', subcategory: 'Oil Change Service' },
    { category: 'Automotive', subcategory: 'Auto Glass Shop' },
    { category: 'Automotive', subcategory: 'Mechanic' },
    { category: 'Automotive', subcategory: 'Car Inspection Station' },
  
    { category: 'Construction & Contractors', subcategory: 'General Contractor' },
    { category: 'Construction & Contractors', subcategory: 'Construction Company' },
    { category: 'Construction & Contractors', subcategory: 'Building Materials Supplier' },
    { category: 'Construction & Contractors', subcategory: 'Excavation Service' },
    { category: 'Construction & Contractors', subcategory: 'Masonry Contractor' },
    { category: 'Construction & Contractors', subcategory: 'Concrete Contractor' },
    { category: 'Construction & Contractors', subcategory: 'Foundation Repair Service' },
  
    { category: 'Finance', subcategory: 'Bank' },
    { category: 'Finance', subcategory: 'Insurance Agency' },
    { category: 'Finance', subcategory: 'Financial Planner' },
    { category: 'Finance', subcategory: 'Investment Service' },
    { category: 'Finance', subcategory: 'Mortgage Lender' },
    { category: 'Finance', subcategory: 'Accounting Service' },
  
    { category: 'Professional Services', subcategory: 'Photographer' },
    { category: 'Professional Services', subcategory: 'Graphic Designer' },
    { category: 'Professional Services', subcategory: 'Web Designer' },
    { category: 'Professional Services', subcategory: 'Private Investigator' },
    { category: 'Professional Services', subcategory: 'Notary Public' },
    { category: 'Professional Services', subcategory: 'Translator' },
  
    { category: 'Event Services', subcategory: 'Event Planner' },
    { category: 'Event Services', subcategory: 'Catering' },
    { category: 'Event Services', subcategory: 'Wedding Venue' },
    { category: 'Event Services', subcategory: 'Party Equipment Rental' },
    { category: 'Event Services', subcategory: 'DJ' },
    { category: 'Event Services', subcategory: 'Photo Booth Rental' },
  
    { category: 'Technology', subcategory: 'Computer Store' },
    { category: 'Technology', subcategory: 'IT Services' },
    { category: 'Technology', subcategory: 'Tech Support' },
    { category: 'Technology', subcategory: 'Web Hosting Service' },
    { category: 'Technology', subcategory: 'Software Company' },
  
    { category: 'Government & Nonprofit', subcategory: 'Government Building' },
    { category: 'Government & Nonprofit', subcategory: 'Nonprofit Organization' },
    { category: 'Government & Nonprofit', subcategory: 'Charity' },
    { category: 'Government & Nonprofit', subcategory: 'Embassy' },
  
    { category: 'Arts, Culture, & Humanities', subcategory: 'Art Gallery' },
    { category: 'Arts, Culture, & Humanities', subcategory: 'Theater' },
    { category: 'Arts, Culture, & Humanities', subcategory: 'Cultural Center' },
    { category: 'Arts, Culture, & Humanities', subcategory: 'Library' },
    { category: 'Arts, Culture, & Humanities', subcategory: 'Historical Place' },
  
    { category: 'Sports & Recreation', subcategory: 'Gym' },
    { category: 'Sports & Recreation', subcategory: 'Yoga Studio' },
    { category: 'Sports & Recreation', subcategory: 'Swimming Pool' },
    { category: 'Sports & Recreation', subcategory: 'Golf Course' },
    { category: 'Sports & Recreation', subcategory: 'Sports Club' },
    { category: 'Sports & Recreation', subcategory: 'Fitness Center' },
  
    { category: 'Weddings', subcategory: 'Wedding Planner' },
    { category: 'Weddings', subcategory: 'Wedding Venue' },
    { category: 'Weddings', subcategory: 'Bridal Shop' },
    { category: 'Weddings', subcategory: 'Florist' },
    { category: 'Weddings', subcategory: 'Wedding Cake Shop' },
    { category: 'Weddings', subcategory: 'Tuxedo Shop' },
  
    { category: 'Local Services', subcategory: 'Handyman' },
    { category: 'Local Services', subcategory: 'Event Photographer' },
    { category: 'Local Services', subcategory: 'Home Inspector' },
    { category: 'Local Services', subcategory: 'Personal Trainer' },
    { category: 'Local Services', subcategory: 'Pet Groomer' }
  ];
  