export const cats = {
  "Business Services": [
    "Accounting",
    "Lawyer",
    "Consultant",
    "Marketing Agency",
    "Real Estate Agency",
    "Architect",
    "Engineer",
  ],
  "Food & Drink": [
    "Restaurant",
    "Coffee Shop",
    "Bakery",
    "Bar",
    "Fast Food Restaurant",
    "Ice Cream Shop",
    "Food Truck",
    "Pizza Restaurant",
    "Vegetarian Restaurant",
    "Wine Bar",
    "Juice Shop",
  ],
  "Health & Medical": [
    "Doctor",
    "Dentist",
    "Chiropractor",
    "Pharmacy",
    "Veterinary Clinic",
    "Physical Therapy Clinic",
    "Optometrist",
    "Mental Health Service",
    "Hospital",
    "Emergency Room",
  ],
  "Home Services": [
    "Plumber",
    "Electrician",
    "HVAC Contractor",
    "Landscaper",
    "Painter",
    "Cleaning Service",
    "Locksmith",
    "Pest Control Service",
    "Carpenter",
    "Roofing Contractor",
  ],
  Retail: [
    "Clothing Store",
    "Electronics Store",
    "Furniture Store",
    "Grocery Store",
    "Bookstore",
    "Jewelry Store",
    "Toy Store",
    "Sporting Goods Store",
    "Hardware Store",
    "Beauty Supply Store",
  ],
  Education: [
    "School",
    "Tutoring Service",
    "University",
    "Language School",
    "College",
    "Music School",
    "Art School",
    "Preschool",
  ],
  Entertainment: [
    "Movie Theater",
    "Amusement Park",
    "Bowling Alley",
    "Concert Hall",
    "Night Club",
    "Dance Studio",
    "Arcade",
    "Museum",
    "Zoo",
    "Comedy Club",
  ],
  "Beauty & Personal Care": [
    "Hair Salon",
    "Nail Salon",
    "Spa",
    "Barber Shop",
    "Massage Therapist",
    "Skin Care Clinic",
    "Tanning Salon",
  ],
  "Travel & Transport": [
    "Car Rental",
    "Travel Agency",
    "Taxi Service",
    "Hotel",
    "Limo Service",
    "Airport Shuttle Service",
    "Moving Company",
    "Bus Station",
    "Train Station",
    "Cruise Agency",
  ],
  Automotive: [
    "Auto Repair Shop",
    "Car Dealership",
    "Auto Body Shop",
    "Car Wash",
    "Tire Shop",
    "Oil Change Service",
    "Auto Glass Shop",
    "Mechanic",
    "Car Inspection Station",
  ],
  "Construction & Contractors": [
    "General Contractor",
    "Construction Company",
    "Building Materials Supplier",
    "Excavation Service",
    "Masonry Contractor",
    "Concrete Contractor",
    "Foundation Repair Service",
  ],
  Finance: [
    "Bank",
    "Insurance Agency",
    "Financial Planner",
    "Investment Service",
    "Mortgage Lender",
    "Accounting Service",
  ],
  "Professional Services": [
    "Photographer",
    "Graphic Designer",
    "Web Designer",
    "Private Investigator",
    "Notary Public",
    "Translator",
  ],
  "Event Services": [
    "Event Planner",
    "Catering",
    "Wedding Venue",
    "Party Equipment Rental",
    "DJ",
    "Photo Booth Rental",
  ],
  Technology: [
    "Computer Store",
    "IT Services",
    "Tech Support",
    "Web Hosting Service",
    "Software Company",
  ],
  "Government & Nonprofit": [
    "Government Building",
    "Nonprofit Organization",
    "Charity",
    "Embassy",
  ],
  "Arts, Culture, & Humanities": [
    "Art Gallery",
    "Theater",
    "Cultural Center",
    "Library",
    "Historical Place",
  ],
  "Sports & Recreation": [
    "Gym",
    "Yoga Studio",
    "Swimming Pool",
    "Golf Course",
    "Sports Club",
    "Fitness Center",
  ],
  Weddings: [
    "Wedding Planner",
    "Wedding Venue",
    "Bridal Shop",
    "Florist",
    "Wedding Cake Shop",
    "Tuxedo Shop",
  ],
  "Local Services": [
    "Handyman",
    "Event Photographer",
    "Home Inspector",
    "Personal Trainer",
    "Pet Groomer",
  ],
};
